#!/bin/bash -
set -eu -o pipefail
cd

# Directory where your backup disk is mounted. No slash at the end!
BACKUP_MOUNT=${BACKUP_MOUNT:-/Volumes/Backup}

# Directory where this program will write logs.
BACKUP_LOGDIR=${BACKUP_LOGDIR:-~/.backup}

mount | grep -qF " on $BACKUP_MOUNT " || \
    { echo "Backup disk not mounted" >&2; exit 1; }

mkdir -p "$BACKUP_LOGDIR"

err=0
sudo nice -n 20 rsync -vax --delete --ignore-errors \
     --exclude /.Spotlight-V100 \
     --exclude /private/var/vm \
     / "$BACKUP_MOUNT/" 2>&1 | tee "$BACKUP_LOGDIR/lastrun.log" || err=1

if (( err )); then
    echo
    echo "==== ERRORS OCCURRED: ===="
    echo
    grep -E ': | failed:' "$BACKUP_LOGDIR/lastrun.log" \
        | tee "$BACKUP_LOGDIR/lasterrors.log"
fi

echo
MINUTES=$(( (SECONDS + 59) / 60 ))  # Bashism.
echo "$MINUTES" >> "$BACKUP_LOGDIR/durations.log"
echo -n "Backup took $MINUTES minutes."
if (( err == 0 )); then echo -n " No errors."; fi
echo

true  # Always "succeed".
